apiVersion: apps/v1
kind: Deployment
metadata:
  name: visit
  labels:
    app: visit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visit
  template:
    metadata:
      labels:
        app: visit
    spec:
      containers:
        - name: visit
          image: skcc017.azurecr.io/visit:latest
          ports:
            - containerPort: 8080